/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthenticatedLayoutRouteImport } from './pages/_authenticated/layout'
import { Route as AuthenticatedPageRouteImport } from './pages/_authenticated/page'
import { Route as DeviceConnectPageRouteImport } from './pages/device-connect/page'
import { Route as InvitePageRouteImport } from './pages/invite/page'
import { Route as LoginPageRouteImport } from './pages/login/page'
import { Route as AuthenticatedAdminPageRouteImport } from './pages/_authenticated/admin/page'
import { Route as AuthenticatedDevicesPageRouteImport } from './pages/_authenticated/devices/page'
import { Route as AuthenticatedServicesPageRouteImport } from './pages/_authenticated/services/page'

const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPageRoute = AuthenticatedPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const DeviceConnectPageRoute = DeviceConnectPageRouteImport.update({
  id: '/device-connect/',
  path: '/device-connect/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitePageRoute = InvitePageRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPageRoute = LoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPageRoute = AuthenticatedAdminPageRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthenticatedDevicesPageRoute =
  AuthenticatedDevicesPageRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedServicesPageRoute =
  AuthenticatedServicesPageRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedPageRoute
  '/device-connect/': typeof DeviceConnectPageRoute
  '/invite/': typeof InvitePageRoute
  '/login/': typeof LoginPageRoute
  '/admin/': typeof AuthenticatedAdminPageRoute
  '/devices/': typeof AuthenticatedDevicesPageRoute
  '/services/': typeof AuthenticatedServicesPageRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedPageRoute
  '/device-connect': typeof DeviceConnectPageRoute
  '/invite': typeof InvitePageRoute
  '/login': typeof LoginPageRoute
  '/admin': typeof AuthenticatedAdminPageRoute
  '/devices': typeof AuthenticatedDevicesPageRoute
  '/services': typeof AuthenticatedServicesPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/': typeof AuthenticatedPageRoute
  '/device-connect/': typeof DeviceConnectPageRoute
  '/invite/': typeof InvitePageRoute
  '/login/': typeof LoginPageRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminPageRoute
  '/_authenticated/devices/': typeof AuthenticatedDevicesPageRoute
  '/_authenticated/services/': typeof AuthenticatedServicesPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/device-connect/'
    | '/invite/'
    | '/login/'
    | '/admin/'
    | '/devices/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device-connect'
    | '/invite'
    | '/login'
    | '/admin'
    | '/devices'
    | '/services'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/device-connect/'
    | '/invite/'
    | '/login/'
    | '/_authenticated/admin/'
    | '/_authenticated/devices/'
    | '/_authenticated/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  DeviceConnectPageRoute: typeof DeviceConnectPageRoute
  InvitePageRoute: typeof InvitePageRoute
  LoginPageRoute: typeof LoginPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedPageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/device-connect/': {
      id: '/device-connect/'
      path: '/device-connect'
      fullPath: '/device-connect/'
      preLoaderRoute: typeof DeviceConnectPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/': {
      id: '/invite/'
      path: '/invite'
      fullPath: '/invite/'
      preLoaderRoute: typeof InvitePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminPageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/devices/': {
      id: '/_authenticated/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AuthenticatedDevicesPageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesPageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedPageRoute: typeof AuthenticatedPageRoute
  AuthenticatedAdminPageRoute: typeof AuthenticatedAdminPageRoute
  AuthenticatedDevicesPageRoute: typeof AuthenticatedDevicesPageRoute
  AuthenticatedServicesPageRoute: typeof AuthenticatedServicesPageRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedPageRoute: AuthenticatedPageRoute,
  AuthenticatedAdminPageRoute: AuthenticatedAdminPageRoute,
  AuthenticatedDevicesPageRoute: AuthenticatedDevicesPageRoute,
  AuthenticatedServicesPageRoute: AuthenticatedServicesPageRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  DeviceConnectPageRoute: DeviceConnectPageRoute,
  InvitePageRoute: InvitePageRoute,
  LoginPageRoute: LoginPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
